Add back output capture

diff --git a/.github/workflows/generate-classes.yml b/.github/workflows/generate-classes.yml
--- a/.github/workflows/generate-classes.yml
+++ b/.github/workflows/generate-classes.yml
@@ -49,7 +49,11 @@ jobs:
 
       - name: Run schematype_to_aqnwb.py to generate AqNWB classes for the LabMetadataExample extension
         run: |
-          python resources/utils/schematype_to_aqnwb.py --generate-test-app demo/labmetadata_extension_demo/spec/ndx-labmetadata-example.namespace.yaml test_output
+          output=$(python resources/utils/schematype_to_aqnwb.py --generate-test-app demo/labmetadata_extension_demo/spec/ndx-labmetadata-example.namespace.yaml test_output2>&1)
+          echo "$output"
+          if echo "$output" | grep -q "ERROR"; then
+            exit 1
+          fi
 
       - name: List generated files
         run: | 
