Update workflow and script to only checkout latest release of the schema repos

diff --git a/.github/workflows/python-utils.yml b/.github/workflows/python-utils.yml
--- a/.github/workflows/python-utils.yml
+++ b/.github/workflows/python-utils.yml
@@ -41,18 +41,14 @@ jobs:
             exit 1
           fi
 
-      - name: Debug resources directory and script path
-        run: |
-          echo "PWD: $PWD"
-          ls -l resources
-          ls -l resources/utils
-          ls -l resources/utils/generate_spec_files.py
-          cat resources/utils/generate_nwb_schema_headers.sh | grep SCRIPT_DIR
-
       - name: Run generate_nwb_schema_headers.sh
         run: |
           chmod +x resources/utils/generate_nwb_schema_headers.sh
-          bash resources/utils/generate_nwb_schema_headers.sh
+          output=$(bash resources/utils/generate_nwb_schema_headers.sh 2>&1)
+          echo "$output"
+          if echo "$output" | grep -q "ERROR"; then
+            exit 1
+          fi
 
       - name: Check generated contents
         run: |
@@ -66,3 +62,6 @@ jobs:
           echo ""
           echo "-----------------code.hpp--------------------"
           cat test_output/core.hpp
+          echo ""
+          echo "-----------------git diff src/spec--------------------"
+          git diff src/spec
